#!/usr/bin/env bash

# Use awk to parse the Apache log file and extract IP and HTTP status code
# Store the result in a new file called "grouped_data"
awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -nr > grouped_data

# Read the "grouped_data" file and format the output as required
# OCCURRENCE_NUMBER IP HTTP_CODE
while read line; do
  OCCURRENCE_NUMBER=$(echo $line | awk '{print $1}')
  IP_HTTP=$(echo $line | awk '{print $2 " " $3}')
  echo "$OCCURRENCE_NUMBER $IP_HTTP"
done < grouped_data